[package]
name = "mastery-chs"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [
    "Jonathan Wid√©n <@cmdjojo>",
    "Leopold Wigbratt <@leopoldwigbratt>"
]
license = "MIT"
description = "A template for Master's Thesis written at Chalmers University of Technology."
repository = "https://github.com/CMDJojo/mastery-chs"
category = ["thesis"]
